create table ADM_ACTIVEDOCUMENT
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"DATASOURCE" VARCHAR2(255) NULL ,
"ACTIVECODE" VARCHAR2(255) NULL ,
"AUTHORNAME" VARCHAR2(255) NULL ,
"AUTHORTIME" NUMBER(19) NULL ,
"AUTHORUNIT" VARCHAR2(255) NULL ,
"PAGES" NUMBER(10) NULL ,
"COPIES" NUMBER(10) NULL ,
"NOTE" VARCHAR2(2000) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL ,
"VERSIONNO" VARCHAR2(255) NULL ,
"ITERATIONNO" VARCHAR2(255) NULL ,
"LATESTINBRANCH" VARCHAR2(1) NULL ,
"LATESTINLEVEL" VARCHAR2(1) NULL ,
"VERSIONLEVEL" NUMBER(10) NULL ,
"VERSIONSORTNO" VARCHAR2(255) NULL ,
"CHECKOUTSTATE" VARCHAR2(255) NULL ,
"DATELOCK" NUMBER(19) NULL ,
"CHECKINNOTE" VARCHAR2(1000) NULL ,
"CREATESTAMP" NUMBER(19) NULL ,
"MODIFYSTAMP" NUMBER(19) NULL ,
"UPDATESTAMP" NUMBER(19) NULL ,
"PREDECESSORID" VARCHAR2(255) NULL ,
"PREDECESSORCLASSID" VARCHAR2(255) NULL ,
"CONTROLBRANCHID" VARCHAR2(255) NULL ,
"CONTROLBRANCHCLASSID" VARCHAR2(255) NULL ,
"LOCKERID" VARCHAR2(255) NULL ,
"LOCKERCLASSID" VARCHAR2(255) NULL ,
"CREATORID" VARCHAR2(255) NULL ,
"CREATORCLASSID" VARCHAR2(255) NULL ,
"MODIFIERID" VARCHAR2(255) NULL ,
"MODIFIERCLASSID" VARCHAR2(255) NULL ,
"STATEID" VARCHAR2(255) NULL ,
"STATENAME" VARCHAR2(255) NULL ,
"LIFECYCLETEMPLATE" VARCHAR2(64) NULL ,
"CREATETIME" NUMBER(19) NULL ,
"MODIFYTIME" NUMBER(19) NULL ,
"CREATEBYID" VARCHAR2(255) NULL ,
"CREATEBYCLASSID" VARCHAR2(255) NULL ,
"MODIFYBYID" VARCHAR2(255) NULL ,
"MODIFYBYCLASSID" VARCHAR2(255) NULL ,
"FOLDERNAME" VARCHAR2(255) NULL ,
"FOLDERID" VARCHAR2(255) NULL ,
"FOLDERCLASSID" VARCHAR2(255) NULL ,
"CONTEXTID" VARCHAR2(255) NULL ,
"CONTEXTCLASSID" VARCHAR2(255) NULL ,
"DOMAINID" VARCHAR2(255) NULL ,
"DOMAINCLASSID" VARCHAR2(255) NULL ,
"MASTERID" VARCHAR2(255) NULL ,
"MASTERCLASSID" VARCHAR2(255) NULL 
)
/
alter table ADM_ACTIVEDOCUMENT add constraint pk_adm__activedocument_iid primary key (innerid) using index tablespace plmindex 
/
CREATE INDEX ADM_ACTIVEDOCUMENT_IDX1 ON ADM_ACTIVEDOCUMENT(FOLDERCLASSID || ':' || FOLDERID)
/
CREATE INDEX ADM_ACTIVEDOCUMENT_IDX2 ON ADM_ACTIVEDOCUMENT(CLASSID || ':' || INNERID)
/
create table ADM_ACTIVEDOCUMENTMASTER
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"ID" VARCHAR2(255) NULL ,
"NAME" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL ,
"SECURITYLEVELID" VARCHAR2(255) NULL ,
"SECURITYLEVELCLASSID" VARCHAR2(255) NULL 
)
/
alter table ADM_ACTIVEDOCUMENTMASTER add constraint pk_adm_activedocmaster_iid primary key (innerid) using index tablespace plmindex 
/
create unique index IDX_ADM_ACTIVEDOCMASTER_ID on ADM_ACTIVEDOCUMENTMASTER(id) tablespace plmindex
/

create table ADM_ACTIVEORDEREDLINK
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"FROMOBJECTID" VARCHAR2(255) NULL ,
"FROMOBJECTCLASSID" VARCHAR2(255) NULL ,
"TOOBJECTID" VARCHAR2(255) NULL ,
"TOOBJECTCLASSID" VARCHAR2(255) NULL ,
"MAINORDERED" NUMBER(10) NULL ,
"ORDEREDBEFORECLASSID" VARCHAR2(255) NULL ,
"ORDEREDBEFOREID" VARCHAR2(255) NULL ,
"ORDEREDBEFOREVERSIONCLASSID" VARCHAR2(255) NULL ,
"ORDEREDBEFOREVERSIONID" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL 
)
/
alter table ADM_ACTIVEORDEREDLINK add constraint pk_link_iid primary key (innerid) using index tablespace plmindex  
/
CREATE INDEX ADM_ACTIVEORDEREDLINK_IDX1 ON ADM_ACTIVEORDEREDLINK(FROMOBJECTCLASSID || ':' || FROMOBJECTID)
/
CREATE INDEX ADM_ACTIVEORDEREDLINK_IDX2 ON ADM_ACTIVEORDEREDLINK(TOOBJECTCLASSID || ':' || TOOBJECTID)
/
CREATE INDEX ADM_ACTIVEORDEREDLINK_IDX3 ON ADM_ACTIVEORDEREDLINK(ORDEREDBEFORECLASSID || ':' || ORDEREDBEFOREID)
/
create table ADM_ACTIVEORDER
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"DATASOURCE" VARCHAR2(255) NULL ,
"ACTIVECODE" VARCHAR2(255) NULL ,
"ACTIVEDOCUMENTID" VARCHAR2(255) NULL ,
"AUTHORNAME" VARCHAR2(255) NULL ,
"AUTHORTIME" NUMBER(19) NULL ,
"AUTHORUNIT" VARCHAR2(255) NULL ,
"PAGES" NUMBER(10) NULL ,
"COPIES" NUMBER(10) NULL ,
"NOTE" VARCHAR2(2000) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL ,
"VERSIONNO" VARCHAR2(255) NULL ,
"ITERATIONNO" VARCHAR2(255) NULL ,
"LATESTINBRANCH" VARCHAR2(1) NULL ,
"LATESTINLEVEL" VARCHAR2(1) NULL ,
"VERSIONLEVEL" NUMBER(10) NULL ,
"VERSIONSORTNO" VARCHAR2(255) NULL ,
"CHECKOUTSTATE" VARCHAR2(255) NULL ,
"DATELOCK" NUMBER(19) NULL ,
"CHECKINNOTE" VARCHAR2(1000) NULL ,
"CREATESTAMP" NUMBER(19) NULL ,
"MODIFYSTAMP" NUMBER(19) NULL ,
"UPDATESTAMP" NUMBER(19) NULL ,
"PREDECESSORID" VARCHAR2(255) NULL ,
"PREDECESSORCLASSID" VARCHAR2(255) NULL ,
"CONTROLBRANCHID" VARCHAR2(255) NULL ,
"CONTROLBRANCHCLASSID" VARCHAR2(255) NULL ,
"LOCKERID" VARCHAR2(255) NULL ,
"LOCKERCLASSID" VARCHAR2(255) NULL ,
"CREATORID" VARCHAR2(255) NULL ,
"CREATORCLASSID" VARCHAR2(255) NULL ,
"MODIFIERID" VARCHAR2(255) NULL ,
"MODIFIERCLASSID" VARCHAR2(255) NULL ,
"STATEID" VARCHAR2(255) NULL ,
"STATENAME" VARCHAR2(255) NULL ,
"LIFECYCLETEMPLATE" VARCHAR2(64) NULL ,
"CREATETIME" NUMBER(19) NULL ,
"MODIFYTIME" NUMBER(19) NULL ,
"CREATEBYID" VARCHAR2(255) NULL ,
"CREATEBYCLASSID" VARCHAR2(255) NULL ,
"MODIFYBYID" VARCHAR2(255) NULL ,
"MODIFYBYCLASSID" VARCHAR2(255) NULL ,
"FOLDERNAME" VARCHAR2(255) NULL ,
"FOLDERID" VARCHAR2(255) NULL ,
"FOLDERCLASSID" VARCHAR2(255) NULL ,
"CONTEXTID" VARCHAR2(255) NULL ,
"CONTEXTCLASSID" VARCHAR2(255) NULL ,
"DOMAINID" VARCHAR2(255) NULL ,
"DOMAINCLASSID" VARCHAR2(255) NULL ,
"MASTERID" VARCHAR2(255) NULL ,
"MASTERCLASSID" VARCHAR2(255) NULL 
)
/
alter table ADM_ACTIVEORDER add constraint pk_adm__activeorder_iid primary key (innerid) using index tablespace plmindex 
/
CREATE INDEX ADM_ACTIVEORDER_IDX1 ON ADM_ACTIVEORDER(FOLDERCLASSID || ':' || FOLDERID)
/
create table ADM_ACTIVEORDERMASTER
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"ID" VARCHAR2(255) NULL ,
"NAME" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL ,
"SECURITYLEVELID" VARCHAR2(255) NULL ,
"SECURITYLEVELCLASSID" VARCHAR2(255) NULL 
)
/
alter table ADM_ACTIVEORDERMASTER add constraint pk_adm_activeordermaster_iid primary key (innerid) using index tablespace plmindex 
/
create unique index IDX_ADM_ACTIVEORDERMASTER_ID on ADM_ACTIVEORDERMASTER(id) tablespace plmindex
/

create table ADM_ACTIVESETLINK
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"FROMOBJECTID" VARCHAR2(255) NULL ,
"FROMOBJECTCLASSID" VARCHAR2(255) NULL ,
"TOOBJECTID" VARCHAR2(255) NULL ,
"TOOBJECTCLASSID" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL 
)
/
alter table ADM_ACTIVESETLINK add constraint pk_adm_activesetlink_iid primary key (innerid) using index tablespace plmindex  
/


create table ADM_ACTIVESET
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"DATASOURCE" VARCHAR2(255) NULL ,
"PAGES" NUMBER(10) NULL ,
"COPIES" NUMBER(10) NULL ,
"ACTIVECODE" VARCHAR2(255) NULL ,
"ACTIVEDOCUMENTID" VARCHAR2(255) NULL ,
"NOTE" VARCHAR2(2000) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL ,
"VERSIONNO" VARCHAR2(255) NULL ,
"ITERATIONNO" VARCHAR2(255) NULL ,
"LATESTINBRANCH" VARCHAR2(1) NULL ,
"LATESTINLEVEL" VARCHAR2(1) NULL ,
"VERSIONLEVEL" NUMBER(10) NULL ,
"VERSIONSORTNO" VARCHAR2(255) NULL ,
"CHECKOUTSTATE" VARCHAR2(255) NULL ,
"DATELOCK" NUMBER(19) NULL ,
"CHECKINNOTE" VARCHAR2(1000) NULL ,
"CREATESTAMP" NUMBER(19) NULL ,
"MODIFYSTAMP" NUMBER(19) NULL ,
"UPDATESTAMP" NUMBER(19) NULL ,
"PREDECESSORID" VARCHAR2(255) NULL ,
"PREDECESSORCLASSID" VARCHAR2(255) NULL ,
"CONTROLBRANCHID" VARCHAR2(255) NULL ,
"CONTROLBRANCHCLASSID" VARCHAR2(255) NULL ,
"LOCKERID" VARCHAR2(255) NULL ,
"LOCKERCLASSID" VARCHAR2(255) NULL ,
"CREATORID" VARCHAR2(255) NULL ,
"CREATORCLASSID" VARCHAR2(255) NULL ,
"MODIFIERID" VARCHAR2(255) NULL ,
"MODIFIERCLASSID" VARCHAR2(255) NULL ,
"STATEID" VARCHAR2(255) NULL ,
"STATENAME" VARCHAR2(255) NULL ,
"LIFECYCLETEMPLATE" VARCHAR2(64) NULL ,
"CREATETIME" NUMBER(19) NULL ,
"MODIFYTIME" NUMBER(19) NULL ,
"CREATEBYID" VARCHAR2(255) NULL ,
"CREATEBYCLASSID" VARCHAR2(255) NULL ,
"MODIFYBYID" VARCHAR2(255) NULL ,
"MODIFYBYCLASSID" VARCHAR2(255) NULL ,
"FOLDERNAME" VARCHAR2(255) NULL ,
"FOLDERID" VARCHAR2(255) NULL ,
"FOLDERCLASSID" VARCHAR2(255) NULL ,
"CONTEXTID" VARCHAR2(255) NULL ,
"CONTEXTCLASSID" VARCHAR2(255) NULL ,
"DOMAINID" VARCHAR2(255) NULL ,
"DOMAINCLASSID" VARCHAR2(255) NULL ,
"MASTERID" VARCHAR2(255) NULL ,
"MASTERCLASSID" VARCHAR2(255) NULL 
)
/
alter table ADM_ACTIVESET add constraint pk_adm__activeset_iid primary key (innerid) using index tablespace plmindex 
/

create table ADM_ACTIVESETMASTER
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"ID" VARCHAR2(255) NULL ,
"NAME" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL ,
"SECURITYLEVELID" VARCHAR2(255) NULL ,
"SECURITYLEVELCLASSID" VARCHAR2(255) NULL 
)
/
alter table ADM_ACTIVESETMASTER add constraint pk_adm_activesetmaster_iid primary key (innerid) using index tablespace plmindex 
/
create unique index IDX_ADM_ACTIVESETMASTER_ID on ADM_ACTIVESETMASTER(id) tablespace plmindex
/

create table ADM_MODELFOLDERLINK
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"FROMOBJECTID" VARCHAR2(255) NULL ,
"FROMOBJECTCLASSID" VARCHAR2(255) NULL ,
"TOOBJECTID" VARCHAR2(255) NULL ,
"TOOBJECTCLASSID" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL 

)
/
alter table ADM_MODELFOLDERLINK add constraint pk_adm_modelfolderlink_iid primary key (innerid) using index tablespace plmindex  
/
CREATE INDEX ADM_MODELFOLDERLINK_IDX1 ON ADM_MODELFOLDERLINK(FROMOBJECTCLASSID || ':' || FROMOBJECTID)
/
CREATE INDEX ADM_MODELFOLDERLINK_IDX2 ON ADM_MODELFOLDERLINK(TOOBJECTCLASSID || ':' || TOOBJECTID)
/

create table ADM_ACTIVEMODEL
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"MODELID" VARCHAR2(255) NULL ,
"MODELNAME" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL 
)
/
alter table ADM_ACTIVEMODEL add constraint pk_adm_activemodel_iid primary key (innerid) using index tablespace plmindex  
/
CREATE INDEX ADM_ACTIVEMODEL_IDX1 ON ADM_ACTIVEMODEL(CLASSID || ':' || INNERID)
/
create table ADM_ACTIVERECYCLE
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"ITEMID" VARCHAR2(255) NULL ,
"ITEMCLASSID" VARCHAR2(255) NULL ,
"ITEMPROPERTIESURL" VARCHAR2(255) NULL ,
"MODELID" VARCHAR2(255) NULL ,
"MODELCLASSID" VARCHAR2(255) NULL ,
"ID" VARCHAR2(255) NULL ,
"NAME" VARCHAR2(255) NULL ,
"SECURITYLEVEL" VARCHAR2(255) NULL ,
"VERSIONNO" VARCHAR2(255) NULL ,
"FOLDERPATH" VARCHAR2(255) NULL ,
"MODELNAME" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL ,
"STATEID" VARCHAR2(255) NULL ,
"STATENAME" VARCHAR2(255) NULL ,
"LIFECYCLETEMPLATE" VARCHAR2(64) NULL 
)
/
alter table ADM_ACTIVERECYCLE add constraint pk_adm_activerecycle_iid primary key (innerid) using index tablespace plmindex  
/
CREATE INDEX ADM_ACTIVERECYCLE_IDX1 ON ADM_ACTIVERECYCLE(CLASSID || ':' ||INNERID)
/
CREATE INDEX ADM_ACTIVERECYCLE_IDX2 ON ADM_ACTIVERECYCLE(ITEMCLASSID || ':' || ITEMID)
/
create table ADM_CONTEXT_ACTIVE
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"ISPRIVATE" CHAR(1) NULL ,
"ID" VARCHAR2(255) NULL ,
"NAME" VARCHAR2(255) NULL ,
"NOTE" VARCHAR2(2000) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL ,
"CREATETIME" NUMBER(19) NULL ,
"MODIFYTIME" NUMBER(19) NULL ,
"CREATEBYID" VARCHAR2(255) NULL ,
"CREATEBYCLASSID" VARCHAR2(255) NULL ,
"MODIFYBYID" VARCHAR2(255) NULL ,
"MODIFYBYCLASSID" VARCHAR2(255) NULL ,
"DOMAINID" VARCHAR2(255) NULL ,
"DOMAINCLASSID" VARCHAR2(255) NULL ,
"CONTEXTID" VARCHAR2(255) NULL ,
"CONTEXTCLASSID" VARCHAR2(255) NULL ,
"SHAREDTEAMID" VARCHAR2(255) NULL ,
"SHAREDTEAMCLASSID" VARCHAR2(255) NULL ,
"LOCALTEAMID" VARCHAR2(255) NULL ,
"LOCALTEAMCLASSID" VARCHAR2(255) NULL ,
"DEFAULTDOMAINID" VARCHAR2(255) NULL ,
"DEFAULTDOMAINCLASSID" VARCHAR2(255) NULL ,
"SYSTEMDOMAINID" VARCHAR2(255) NULL ,
"SYSTEMDOMAINCLASSID" VARCHAR2(255) NULL ,
"DEFAULTCABINETID" VARCHAR2(255) NULL ,
"DEFAULTCABINETCLASSID" VARCHAR2(255) NULL ,
"SYSTEMCABINETID" VARCHAR2(255) NULL ,
"SYSTEMCABINETCLASSID" VARCHAR2(255) NULL 
)
/
alter table ADM_CONTEXT_ACTIVE add constraint pk_adm_context_active_iid primary key (innerid) using index tablespace plmindex  
/
create unique index IDX_ADM_CONTEXT_ACTIVE_ID on ADM_CONTEXT_ACTIVE(id) tablespace plmindex
/


create table ADM_QUERYSCHEMA
(
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NULL ,
"SCHEMANAME" VARCHAR2(255) NULL ,
"ACTIVENAME" VARCHAR2(255) NULL ,
"DEFAULTSCHEMA" NUMBER(10) NULL ,
"BEGINTIME" VARCHAR2(255) NULL ,
"ENDTIME" VARCHAR2(255) NULL ,
"LIFECYCLE" VARCHAR2(255) NULL ,
"ACTIVEMODELID" VARCHAR2(255) NULL ,
"ACTIVEMODELNAME" VARCHAR2(255) NULL ,
"GROUPCONDITION" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL ,
"CREATETIME" NUMBER(19) NULL ,
"MODIFYTIME" NUMBER(19) NULL ,
"CREATEBYID" VARCHAR2(255) NULL ,
"CREATEBYCLASSID" VARCHAR2(255) NULL ,
"MODIFYBYID" VARCHAR2(255) NULL ,
"MODIFYBYCLASSID" VARCHAR2(255) NULL 
)
/
alter table ADM_QUERYSCHEMA add constraint pk_adm_queryschema_iid primary key (innerid) using index tablespace plmindex  
/

CREATE OR REPLACE FUNCTION DATETOLONG (jdate IN DATE)
RETURN NUMBER
AS
BEGIN
	RETURN (jdate - TO_DATE('1970-01-01:08:00:00', 'YYYY-MM-DD:HH24:MI:SS'))*86400000;
END;
/

CREATE OR REPLACE FUNCTION LONGTODATE (jdate IN NUMBER)
RETURN DATE
AS
BEGIN
	RETURN TO_DATE('1970-01-01:08:00:00', 'YYYY-MM-DD:HH24:MI:SS')+floor(jdate/1000)/86400;
END;
/

CREATE OR REPLACE
    VIEW V_ADM_STATISTICS(
        INNERID
        ,CLASSID
        ,DATASOURCE
        ,AUTHORNAME
        ,AUTHORTIME
        ,AUTHORUNIT
        ,FOLDERID
        ,FOLDERCLASSID
        ,PAGES
        ,COUNT
        ,ADM_COUNT
        ,NOTE
        ,CREATETIME
        ,CREATE_TIME
        ,MODIFYTIME
        ,MODIFY_TIME
        ,CREATEBY
        ,CREATOR
        ,MODIFYBY
        ,MODIFIER
        ,UPDATE_TIME
        ,STATENAME
        ,LIFECYCLE_STATE
        ,VERSIONNO
        ,VERSION
        ,FOLDER_INNERID
        ,CONTEXT_INNERID
        ,DOMAIN_INNERID
        ,LIFECYCLE_TEMPLATE
        ,ID
        ,NAME
        ,SLNAME
        ,SECLEVEL
        ,SECURITYLEVELID
        ,SECURITYLEVELCLASSID
        ,ACTIVECODE
        ,ACTIVECODENAME
        ,FILEID
        ,FILECLASSID
    ) AS
        SELECT
                DISTINCT a.INNERID
                ,a.CLASSID
                ,a.dataSource
                ,-- 数据来源
                A.AUTHORNAME
                ,-- 作者名称
                TO_CHAR(LONGTODATE(A.AUTHORTIME), 'YYYY-MM-DD') AUTHORTIME
                ,-- 文件编制时间
                A.AUTHORUNIT
                ,-- 作者所属单位
                A.FOLDERID
                ,A.FOLDERCLASSID
                ,a.pages
                ,-- 页数
                a.COPIES COUNT
                ,a.COPIES ADM_COUNT
                ,-- 份数
                a.note
                ,-- 备注
                a.createTime
                ,-- 创建时间
                TO_CHAR(LONGTODATE(A.createTime), 'YYYY-MM-DD') create_Time
                ,a.modifyTime
                ,-- 修改时间
                TO_CHAR(LONGTODATE(A.modifyTime), 'YYYY-MM-DD') MODIFY_TIME
                ,E.USERNAME createBy
                ,-- 创建人
                E.USERNAME CREATOR
                ,F.USERNAME modifyBy
                ,-- 修改人
                F.USERNAME MODIFIER
                ,TO_CHAR(LONGTODATE(A.UPDATETIME), 'YYYY-MM-DD HH24:MI:SS') UPDATE_TIME
                ,-- 物理更新时间
                a.STATENAME
                ,-- 生命周期名称
                a.STATENAME LIFECYCLE_STATE
                ,-- 版本信息
                a.VERSIONNO
                ,-- 版本号
                a.VERSIONNO VERSION
                ,-- 版本号
                a.FOLDERID FOLDER_INNERID
                ,-- 文件夹OID
                A.CONTEXTID CONTEXT_INNERID
                ,-- 站点信息
                A.DOMAINID DOMAIN_INNERID
                ,-- 域信息
                A.LIFECYCLETEMPLATE LIFECYCLE_TEMPLATE
                ,-- 生命周期模板
                B.ID
                ,-- 现行文件主对象.编号
                B.NAME
                ,-- 现行文件主对象.名称
                D.SLNAME
                ,-- 现行文件主对象.密级
                d.SLNAME SECLEVEL
                ,B.SECURITYLEVELID
                ,B.SECURITYLEVELCLASSID -- 代号
                ,A.ACTIVECODE
                ,DAC.ITEMVALUE ACTIVECODENAME -- 附件
                ,G.REFID AS FILEID
                ,-- 现行文件附件标识
                G.REFTYPE AS FILECLASSID -- 现行文件附件类标识
            FROM
                ADM_ACTIVEDOCUMENT A
                ,-- 现行文件
                ADM_ACTIVEDOCUMENTMASTER B
                ,-- 现行文件主对象
                PLM_SYSTEM_SECURITY_LEVEL C
                ,-- 密级
                (
                    SELECT
                            PCB.MASTERID
                            ,PCB.MASTERCLASSID
                            ,MAX(MODIFYSTAMP) MODIFYSTAMP
                        FROM
                            PT_OM_CONTROLBRANCH PCB
                        GROUP BY
                            PCB.MASTERID
                            ,PCB.MASTERCLASSID
                ) CB1
                ,PT_OM_CONTROLBRANCH CB2
                ,-- 版本控制
                AASECLEVELDATA D
                ,(
                    SELECT
                            Y.USERNAME
                            ,Y.USERID
                            ,X.INNERID
                            ,X.CLASSID
                        FROM
                            PLM_PRINCIPAL_USER X
                            ,AAUSERDATA Y
                        WHERE
                            X.AAUSERINNERID = Y.INNERID
                ) E
                ,-- 用户
                (
                    SELECT
                            N.USERNAME
                            ,N.USERID
                            ,M.INNERID
                            ,M.CLASSID
                        FROM
                            PLM_PRINCIPAL_USER M
                            ,AAUSERDATA N
                        WHERE
                            M.AAUSERINNERID = N.INNERID
                ) F
                ,-- 用户
                (
                    SELECT
                            PLUI.ITEMID
                            ,PLUI.ITEMVALUE
                        FROM
                            PT_MT_LOOKUPITEM PLUI
                        WHERE
                            PLUI.LOOKUPID = 'activeCode'
                ) DAC
                ,-- 数据字典代号
                PTOBJTOLINK G --附件LINK
            WHERE
                A.MASTERID = B.INNERID
                AND A.MASTERCLASSID = B.CLASSID
                AND B.SECURITYLEVELID = C.INNERID
                AND B.SECURITYLEVELCLASSID = C.CLASSID
                AND C.AASECURITYLEVELINNERID = D.IID
                AND A.CONTROLBRANCHID = CB2.INNERID
                AND A.CONTROLBRANCHCLASSID = CB2.CLASSID
                AND B.INNERID = CB1.MASTERID
                AND B.CLASSID = CB1.MASTERCLASSID
                AND CB1.MODIFYSTAMP = CB2.MODIFYSTAMP
                AND A.CREATEBYID = E.INNERID
                AND A.CREATEBYCLASSID = E.CLASSID
                AND A.MODIFYBYID = F.INNERID
                AND A.MODIFYBYCLASSID = F.CLASSID
                AND A.INNERID = G.REFID(+)
                AND A.CLASSID = G.REFTYPE(+)
                AND A.ACTIVECODE = DAC.ITEMID(+)

/

