CREATE TABLE "DDM_DC_A3_TASK_SIGNATURE" (
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NOT NULL ,
"DEALUSERIID" VARCHAR2(64) NULL ,
"DEALUSERID" VARCHAR2(64) NULL ,
"DEALUSERNAME" VARCHAR2(128) NULL ,
"DEALDEVISIONIID" VARCHAR2(64) NULL ,
"DEALDEVISIONID" VARCHAR2(64) NULL ,
"DEALDEVISIONNAME" VARCHAR2(128) NULL ,
"DEALROLE" VARCHAR2(64) NULL ,
"ISAGREE" NUMBER(1) NULL ,
"DEALMIND" VARCHAR2(512) NULL ,
"MINDTYPE" VARCHAR2(16) NULL ,
"ISNEEDDEVISIONMIND" NUMBER(1) NULL ,
"STARTTIME" NUMBER NULL ,
"SIGNATURETIME" NUMBER NULL ,
"SIGNATURESTATE" NUMBER NULL ,
"DOMAINIID" VARCHAR2(64) NULL ,
"ORDERIID" VARCHAR2(64) NULL ,
"TASKIID" VARCHAR2(64) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL 
)
/

COMMENT ON TABLE "DDM_DC_A3_TASK_SIGNATURE" IS 'A3签署信息'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."INNERID" IS '内部标识'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."CLASSID" IS '类名'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."DEALUSERIID" IS '处理人标识'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."DEALUSERID" IS '处理人编号'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."DEALUSERNAME" IS '处理人名称'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."DEALDEVISIONIID" IS '处理人部门标识'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."DEALDEVISIONID" IS '处理人部门编号'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."DEALDEVISIONNAME" IS '处理人部门名称'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."DEALROLE" IS '处理人角色'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."ISAGREE" IS '是否同意'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."DEALMIND" IS '处理意见'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."MINDTYPE" IS '意见类型'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."ISNEEDDEVISIONMIND" IS '是否需要单位意见'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."STARTTIME" IS '任务开始时间'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."SIGNATURETIME" IS '签署时间'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."DOMAINIID" IS '域标识'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."ORDERIID" IS '单据标识'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."TASKIID" IS '任务标识'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."UPDATETIME" IS '系统用来支持并发的字段'
/
COMMENT ON COLUMN "DDM_DC_A3_TASK_SIGNATURE"."UPDATECOUNT" IS '系统用来支持并发的字段'
/

CREATE INDEX "INDEX_SIGNATURE_ORDERIID"
ON "DDM_DC_A3_TASK_SIGNATURE" ("ORDERIID" ASC)
/
CREATE INDEX "INDEX_SIGNATURE_TASKIID"
ON "DDM_DC_A3_TASK_SIGNATURE" ("TASKIID" ASC)
/
ALTER TABLE "DDM_DC_A3_TASK_SIGNATURE" ADD PRIMARY KEY ("INNERID")
/


CREATE TABLE "DDM_DC_A3_SIGOBJLINK" (
"INNERID" VARCHAR2(255) NOT NULL ,
"CLASSID" VARCHAR2(255) NOT NULL ,
"FROMOBJECTID" VARCHAR2(255) NULL ,
"FROMOBJECTCLASSID" VARCHAR2(255) NULL ,
"TOOBJECTID" VARCHAR2(255) NULL ,
"TOOBJECTCLASSID" VARCHAR2(255) NULL ,
"UPDATETIME" NUMBER(19) NULL ,
"UPDATECOUNT" NUMBER(10) NULL 
)
/
COMMENT ON TABLE "DDM_DC_A3_SIGOBJLINK" IS '发放单与分发数据link表'
/
COMMENT ON COLUMN "DDM_DC_A3_SIGOBJLINK"."INNERID" IS '内部标识'
/
COMMENT ON COLUMN "DDM_DC_A3_SIGOBJLINK"."CLASSID" IS '类名'
/
COMMENT ON COLUMN "DDM_DC_A3_SIGOBJLINK"."FROMOBJECTID" IS '发放单内部标识'
/
COMMENT ON COLUMN "DDM_DC_A3_SIGOBJLINK"."FROMOBJECTCLASSID" IS '发放单类名'
/
COMMENT ON COLUMN "DDM_DC_A3_SIGOBJLINK"."TOOBJECTID" IS '分发数据源内部标识'
/
COMMENT ON COLUMN "DDM_DC_A3_SIGOBJLINK"."TOOBJECTCLASSID" IS '分发数据源类名'
/
COMMENT ON COLUMN "DDM_DC_A3_SIGOBJLINK"."UPDATETIME" IS '系统用来支持并发的字段'
/
COMMENT ON COLUMN "DDM_DC_A3_SIGOBJLINK"."UPDATECOUNT" IS '系统用来支持并发的字段'
/


CREATE INDEX "DDM_DC_A3_SIGOBJLINK_IDX1"
ON "DDM_DC_A3_SIGOBJLINK" ("INNERID" ASC)
/
CREATE INDEX "DDM_DC_A3_SIGOBJLINK_IDX2"
ON "DDM_DC_A3_SIGOBJLINK" ("FROMOBJECTID" ASC)
/
CREATE INDEX "DDM_DC_A3_SIGOBJLINK_IDX3"
ON "DDM_DC_A3_SIGOBJLINK" ("TOOBJECTID" ASC)
/
ALTER TABLE "DDM_DC_A3_SIGOBJLINK" ADD PRIMARY KEY ("INNERID")
/