--追加人  ：		许国政
--追加原因：		七部提出需求加工单增加显示"发放单创建者"字段
alter table DDM_DIS_PAPERTASK add DISORDERCREATOR  VARCHAR2(255)
/
--纸质任务添加"发放单创建者"字段后，更新既存数据的该字段值
UPDATE DDM_DIS_PAPERTASK DDP
SET DISORDERCREATOR = (
	SELECT
		RTN.USERNAME
	FROM
		(
			SELECT DISTINCT
				P .INNERID,
				A .USERNAME
			FROM
				DDM_DIS_PAPERTASK P,
				DDM_DIS_TASKINFOLINK TIL,
				DDM_DIS_INFO I,
				DDM_DIS_ORDEROBJLINK OOL,
				DDM_DIS_ORDER O,
				PLM_PRINCIPAL_USER U,
				AAUSERDATA A
			WHERE
				P .INNERID = TIL.FROMOBJECTID (+)
			AND TIL.TOOBJECTID = I.INNERID
			AND I.DISORDEROBJLINKID = OOL.INNERID
			AND OOL.FROMOBJECTID = O.INNERID
			AND O.CREATEBYID = U .INNERID (+)
			AND U .AAUSERINNERID = A .INNERID
		) RTN
	WHERE
		DDP.INNERID = RTN.INNERID
)
/
